### ISSUE TITLE
switch out geocoding engine

### ISSUE THREAD

**Issue by wilsaj** [open-austin/construction-permits#16]
From the Google Maps geocoder to something that can be freely re-served. The TOS is kind of obtuse, but [their FAQ](https://developers.google.com/maps/faq#geocoder_exists) is pretty explicit:

> Please be aware of the usage limits that apply to geocoder requests, and note that use of the geocoder for any purpose other than obtaining locations that will be displayed using the Google Maps APIs is a violation of the Terms of Service.

**Comment by wilsaj** [comment]
Looked over a few options and I think mapzen search is probably the best at the moment because it sources OpenAddresses and OSM. OpenAddresses directly references city of Austin's address data, and OSM indirectly does now that we've imported those into OSM.

Other good ones are:
- Mapquest or Nominatim (OSM only)
- OpenCage (based on various open data sources, but the rate limit is lower than mapzen and it's not clear whether or not they source OpenAddresses)

**Comment by wilsaj** [comment]
The only thing that is lost in the switch is that county field is usually going to be blank, but county boundaries are well defined and super easy to look up for a given point.

**Comment by spatialaustin** [comment]
Sounds like a great idea.

Will definitely need to test how well mapzen interpolates addresses when an an exact match isn't found. A small % of permits are issued for new construction at addresses that don't exist (yet).
